import Link from 'next/link';
import { notFound } from 'next/navigation';
import { writing } from '../../content';
import { SiteFooter, SiteHeader } from '@/components/site-chrome';

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = writing.find((item) => item.slug === slug);
  if (!article) notFound();
  return <main className="site-shell"><SiteHeader /><article className="article-layout"><section><Link className="article-category" href="/writing"><span>← 返回写作</span><b>{article.category}</b><em>{article.label}</em></Link><h1>{article.title}</h1><p className="article-lead">{article.excerpt}</p><div className="article-meta">开发阿雷 · {article.date} · {article.meta}</div><div className="markdown-body"><p>一件产品被人使用时，用户通常不会看见它背后的判断：删掉了哪些选择，保留了哪些摩擦，又在哪些时刻决定停止继续优化。写下这些过程，不是为了给答案增加包装，而是为了把可复查的路径留在现场。</p><p>这是一篇用于验证长文阅读体验的示例内容。未来接入后台后，正文将由 Markdown 字段直接提供；标题、段落、引用、列表和表格都应保留自身的阅读节奏。</p><h2 id="problem">从问题开始，而不是从界面开始</h2><p>开始制作之前，先把问题说得足够具体。所谓“界面不好用”常常只是一种表面描述，它可能意味着信息被放在了错误的顺序，可能意味着用户没有建立起正确的预期，也可能只是某个动作的反馈来得太晚。</p><p>因此我会把模糊的反馈改写成可观察的句子：谁在什么情境下，试图完成什么动作，在哪里犹豫，以及这次犹豫造成了什么后果。句子越清楚，后面的设计选择就越不依赖直觉。</p><blockquote>当信息变得复杂，真正需要被设计的，往往是理解它的路径。</blockquote><p>这个过程并不浪漫。它意味着需要拒绝一部分看起来精致的方案，也意味着要承认某些内容暂时没有合适的位置。但这正是内容系统与单个页面的区别：前者需要为变化预留空间。</p><h2 id="structure">让结构参与表达</h2><p>长文的结构不只是排版问题。标题是停靠点，段落是呼吸，列表让并列关系显形，引用则提供一次必要的停顿。当这些元素拥有稳定的视觉规则，读者便可以先扫描再深入，也能在下次回来时迅速定位。</p><ul><li>先让阅读目标可见，而不是急着展示全部信息。</li><li>把可重复的动作变成一致的入口与反馈。</li><li>在页面边缘留下目录、时间与分类等可回溯的信息。</li></ul><p>下面是一组简单的判断记录。它不提供万能模板，却能帮助团队把讨论从“我更喜欢”推进到“这是否解决了当前的问题”。</p><table><thead><tr><th>观察</th><th>可能原因</th><th>下一步</th></tr></thead><tbody><tr><td>用户反复返回上一层</td><td>入口名称与预期不一致</td><td>核对命名与信息层级</td></tr><tr><td>阅读在首屏中断</td><td>摘要没有给出明确价值</td><td>重写开头与关键小标题</td></tr><tr><td>内容无法被再次找到</td><td>分类与检索字段不足</td><td>补充主题、系列与标签</td></tr></tbody></table><h2 id="details">把细节放回使用现场</h2><p>体验质量往往不在某个大动作上，而在许多小动作是否前后一致：一个链接是否明确可点，一段说明是否足够短，一个空状态是否告诉人下一步。把这些细节放回真实的时间线里检查，能避免设计只在静态稿中成立。</p><p>对于个人工作站而言，内容还会不断增长。今天的一篇文章、一个项目片段或一则说说，未来都可能成为新的关联入口。页面应该容纳这种积累，而不是把每一次新增都变成一次重新设计。</p><h2 id="conclusion">继续阅读</h2><p>写作的价值不止是发布时的完成感。更重要的是，在数月之后回看时，仍然能辨认当时的语境、依据和犹豫。一个清晰的目录、可点击的分类、稳定的排版，会让这些留下来的内容真正重新被使用。</p><p>到这里，示例长文结束。后续后台接入时，只需替换正文内容，阅读页面的结构与样式会继续承载新的文章。</p></div></section><aside className="article-toc"><p>文章目录</p><span>CONTENTS / 04</span><a href="#problem"><b>01</b>从问题开始</a><a href="#structure"><b>02</b>让结构参与表达</a><a href="#details"><b>03</b>把细节放回使用现场</a><a href="#conclusion"><b>04</b>继续阅读</a></aside></article><SiteFooter /></main>;
}
