'use client';
import { CmsText } from '@/components/cms-text';

import { useContent } from '@/components/content-provider';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Code2, Mail, MessageCircle, ScanLine } from 'lucide-react';

import './about-profile.css';

export function AboutProfile() {
  const { profile } = useContent();
  return <div className="profile-page">
    <header className="profile-index"><div className="profile-index-name"><span className="profile-index-mark" aria-hidden="true"><CmsText page="关于页" name="01 A /" /></span><div><p className="profile-kicker"><CmsText page="关于页" name="02 开发 / 记录 / 探索" /></p><h1>{profile.name}</h1></div></div><p><CmsText page="关于页" name="03 用代码做点东西，" /><br /><CmsText page="关于页" name="04 用文字留住过程。" /></p><div className="profile-index-links"><a href="#profile-service"><CmsText page="关于页" name="05 01 技术服务" /><ArrowUpRight size={14} /></a><a href="#profile-contact"><CmsText page="关于页" name="06 02 关注与联系" /><ArrowUpRight size={14} /></a><a href="#profile-platforms"><CmsText page="关于页" name="07 03 平台索引" /><ArrowUpRight size={14} /></a></div></header>
    <section className="profile-service" id="profile-service"><div className="profile-service-number" aria-hidden="true"><CmsText page="关于页" name="08 &lt;/&gt;" /></div><div><p className="profile-kicker"><CmsText page="关于页" name="09 01 / 技术服务" /></p><h2><CmsText page="关于页" name="10 让想法，再向前一步。" /></h2><p><CmsText page="关于页" name="11 技术服务与购买入口，项目、价格及交付" /></p><a href={profile.serviceUrl} target="_blank" rel="noopener noreferrer"><CmsText page="关于页" name="12 查看服务与购买" /><ArrowUpRight size={20} /></a></div><span className="profile-service-address"><CmsText page="关于页" name="13 SHOP.QQPHP.COM" /></span></section>
    <section className="profile-connect" id="profile-contact"><article className="profile-account"><div><p className="profile-kicker"><CmsText page="关于页" name="14 02 / 微信公众号" /></p><h2><CmsText page="关于页" name="15 微信公众号 · 开发阿雷" /></h2><p><CmsText page="关于页" name="16 搜索公众号「开发阿雷」，关注新的记录" /></p><div className="profile-account-name"><MessageCircle size={19} />{profile.name}<span><CmsText page="关于页" name="17 微信公众号" /></span></div></div><div className="profile-qr">{profile.publicAccountQr ? <Image src={profile.publicAccountQr} alt="开发阿雷微信公众号二维码，使用微信扫码关注" width={220} height={220} /> : <div className="profile-qr-pending"><ScanLine size={38} /><strong><CmsText page="关于页" name="18 公众号二维码" /></strong><span><CmsText page="关于页" name="19 图片待补充" /></span></div>}<p>{profile.publicAccountQr ? '微信扫一扫 · 关注开发阿雷' : '也可以在微信内搜索「开发阿雷」'}</p></div></article><aside className="profile-contact"><p className="profile-kicker"><CmsText page="关于页" name="20 打个招呼" /></p><h2><CmsText page="关于页" name="21 微信与邮箱" /></h2><div><MessageCircle size={18} /><span><CmsText page="关于页" name="22 联系微信" /><strong>{profile.wechat || '微信号待补充'}</strong></span></div><div><Mail size={18} /><span><CmsText page="关于页" name="23 联系邮箱" />{profile.email ? <a href={`mailto:${profile.email}`}>{profile.email} ↗</a> : <strong><CmsText page="关于页" name="24 邮箱待补充" /></strong>}</span></div></aside></section>
    <section className="profile-platforms" id="profile-platforms"><div className="profile-platform-heading"><div><p className="profile-kicker"><CmsText page="关于页" name="25 03 / 散落在互联网" /></p><h2><CmsText page="关于页" name="26 平台索引" /></h2></div><p><CmsText page="关于页" name="27 不同的入口，同一个开发阿雷。" /></p></div><div className="profile-platform-grid">{profile.platforms.map((platform, i) => { const contents = <><span>{String(i + 1).padStart(2, '0')}</span><h3>{platform.name}</h3><p>{platform.label}</p><small>{platform.url ? '前往个人主页 ↗' : '个人主页待补充'}</small></>; return platform.url ? <a href={platform.url} target="_blank" rel="noopener noreferrer" key={platform.name}>{contents}</a> : <article key={platform.name}>{contents}</article>; })}</div></section>
    <section className="profile-interests" aria-label="认识我的几个入口"><div className="profile-section-label"><span><CmsText page="关于页" name="28 04 / 不止一面" /></span><h2><CmsText page="关于页" name="29 从这些小事，" /><br /><CmsText page="关于页" name="30 认识我。" /></h2></div><Link href="/projects" className="profile-interest"><Code2 size={24} /><h3><CmsText page="关于页" name="31 把想法做出来" /></h3><p><CmsText page="关于页" name="32 看看那些从问题出发、逐渐成形的小项目" /></p><span><CmsText page="关于页" name="33 打开项目档案 ↗" /></span></Link><Link href="/writing" className="profile-interest"><span className="profile-symbol" aria-hidden="true">Aa</span><h3><CmsText page="关于页" name="34 给思考留个底稿" /></h3><p><CmsText page="关于页" name="35 写下理解的过程，也留下还没有答案的问" /></p><span><CmsText page="关于页" name="36 翻翻我的写作 ↗" /></span></Link><Link href="/hobbies" className="profile-interest"><span className="profile-symbol" aria-hidden="true">✳</span><h3><CmsText page="关于页" name="37 认真地玩一会儿" /></h3><p><CmsText page="关于页" name="38 音乐、影像和日常里的小发现，都是新的" /></p><span><CmsText page="关于页" name="39 去生活里逛逛 ↗" /></span></Link></section>
    <div className="profile-signoff"><p><CmsText page="关于页" name="40 保持好奇，" /><span><CmsText page="关于页" name="41 继续动手。" /></span></p><span aria-hidden="true"><CmsText page="关于页" name="42 开发阿雷 / 持续生长中" /></span></div>
  </div>;
}
